apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-flutter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-flutter-app
  template:
    metadata:
      labels:
        app: gitops-flutter-app
    spec:
      containers:
        - name: flutter-app
          image:satpatil75/ gitops-flutter-app:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 80
